const actionTypes = {
    LOGIN: 'LOGIN',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',

    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',

    LOGOUT: 'LOGOUT',

    //manager admin
    ADD_ADMIN_SUCCESS: 'ADD_ADMIN_SUCCESS',
    ADD_ADMIN_FAIL: 'ADD_ADMIN_FAIL',

    GET_ALL_ADMIN_SUCCESS: 'GET_ALL_ADMIN_SUCCESS',
    GET_ALL_ADMIN_FAIL: 'GET_ALL_ADMIN_FAIL',

    GET_AN_ADMIN_SUCCESS: 'GET_AN_ADMIN_SUCCESS',
    GET_AN_ADMIN_FAIL: 'GET_AN_ADMIN_FAIL',

    PUT_ADMIN_SUCCESS: 'PUT_ADMIN_SUCCESS',
    PUT_ADMIN_FAIL: 'PUT_ADMIN_FAIL',

    DELETE_ADMIN_SUCCESS: 'DELETE_ADMIN_SUCCESS',
    DELETE_ADMIN_FAIL: 'DELETE_ADMIN_FAIL',

    //manager user
    GET_ALL_USER_SUCCESS: 'GET_ALL_USER_SUCCESS',
    GET_ALL_USER_FAIL: 'GET_ALL_USER_FAIL',

    GET_AN_USER_SUCCESS: 'GET_AN_USER_SUCCESS',
    GET_AN_USER_FAIL: 'GET_AN_USER_FAIL',

    //manager category

    ADD_CATEGORY_SUCCESS: 'ADD_CATEGORY_SUCCESS',
    ADD_CATEGORY_FAIL: 'ADD_CATEGORY_FAIL',

    GET_ALL_CATEGORY_SUCCESS: 'GET_ALL_CATEGORY_SUCCESS',
    GET_ALL_CATEGORY_FAIL: 'GET_ALL_CATEGORY_FAIL',

    GET_AN_CATEGORY_SUCCESS: 'GET_AN_CATEGORY_SUCCESS',
    GET_AN_CATEGORY_FAIL: 'GET_AN_CATEGORY_FAIL',

    PUT_CATEGORY_SUCCESS: 'PUT_CATEGORY_SUCCESS',
    PUT_CATEGORY_FAIL: 'PUT_CATEGORY_FAIL',

    DELETE_CATEGORY_SUCCESS: 'DELETE_CATEGORY_SUCCESS',
    DELETE_CATEGORY_FAIL: 'DELETE_CATEGORY_FAIL',
};

export default actionTypes;
