const actionTypes = {
    LOGIN: 'LOGIN',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',

    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',

    LOGOUT: 'LOGOUT',

    //get current user

    GET_CURRENT_USER_SUCCESS: 'GET_CURRENT_USER_SUCCESS',
    GET_CURRENT_USER_FAIL: 'GET_CURRENT_USER_FAIL',

    //manager admin
    ADD_ADMIN_SUCCESS: 'ADD_ADMIN_SUCCESS',
    ADD_ADMIN_FAIL: 'ADD_ADMIN_FAIL',

    GET_ALL_ADMIN_SUCCESS: 'GET_ALL_ADMIN_SUCCESS',
    GET_ALL_ADMIN_FAIL: 'GET_ALL_ADMIN_FAIL',

    GET_AN_ADMIN_SUCCESS: 'GET_AN_ADMIN_SUCCESS',
    GET_AN_ADMIN_FAIL: 'GET_AN_ADMIN_FAIL',

    PUT_ADMIN_SUCCESS: 'PUT_ADMIN_SUCCESS',
    PUT_ADMIN_FAIL: 'PUT_ADMIN_FAIL',

    DELETE_ADMIN_SUCCESS: 'DELETE_ADMIN_SUCCESS',
    DELETE_ADMIN_FAIL: 'DELETE_ADMIN_FAIL',

    //manager user
    GET_ALL_USER_SUCCESS: 'GET_ALL_USER_SUCCESS',
    GET_ALL_USER_FAIL: 'GET_ALL_USER_FAIL',

    GET_AN_USER_SUCCESS: 'GET_AN_USER_SUCCESS',
    GET_AN_USER_FAIL: 'GET_AN_USER_FAIL',

    //manager category

    ADD_CATEGORY_SUCCESS: 'ADD_CATEGORY_SUCCESS',
    ADD_CATEGORY_FAIL: 'ADD_CATEGORY_FAIL',

    GET_ALL_CATEGORY_SUCCESS: 'GET_ALL_CATEGORY_SUCCESS',
    GET_ALL_CATEGORY_FAIL: 'GET_ALL_CATEGORY_FAIL',

    GET_AN_CATEGORY_SUCCESS: 'GET_AN_CATEGORY_SUCCESS',
    GET_AN_CATEGORY_FAIL: 'GET_AN_CATEGORY_FAIL',

    PUT_CATEGORY_SUCCESS: 'PUT_CATEGORY_SUCCESS',
    PUT_CATEGORY_FAIL: 'PUT_CATEGORY_FAIL',

    DELETE_CATEGORY_SUCCESS: 'DELETE_CATEGORY_SUCCESS',
    DELETE_CATEGORY_FAIL: 'DELETE_CATEGORY_FAIL',

    //manager color

    ADD_COLOR_SUCCESS: 'ADD_COLOR_SUCCESS',
    ADD_COLOR_FAIL: 'ADD_COLOR_FAIL',

    GET_ALL_COLOR_SUCCESS: 'GET_ALL_COLOR_SUCCESS',
    GET_ALL_COLOR_FAIL: 'GET_ALL_COLOR_FAIL',

    GET_AN_COLOR_SUCCESS: 'GET_AN_COLOR_SUCCESS',
    GET_AN_COLOR_FAIL: 'GET_AN_COLOR_FAIL',

    PUT_COLOR_SUCCESS: 'PUT_COLOR_SUCCESS',
    PUT_COLOR_FAIL: 'PUT_COLOR_FAIL',

    DELETE_COLOR_SUCCESS: 'DELETE_COLOR_SUCCESS',
    DELETE_COLOR_FAIL: 'DELETE_COLOR_FAIL',

    //manager product

    ADD_PRODUCT_SUCCESS: 'ADD_PRODUCT_SUCCESS',
    ADD_PRODUCT_FAIL: 'ADD_PRODUCT_FAIL',

    GET_ALL_PRODUCT_SUCCESS: 'GET_ALL_PRODUCT_SUCCESS',
    GET_ALL_PRODUCT_FAIL: 'GET_ALL_PRODUCT_FAIL',

    GET_AN_PRODUCT_SUCCESS: 'GET_AN_PRODUCT_SUCCESS',
    GET_AN_PRODUCT_FAIL: 'GET_AN_PRODUCT_FAIL',

    PUT_PRODUCT_SUCCESS: 'PUT_PRODUCT_SUCCESS',
    PUT_PRODUCT_FAIL: 'PUT_PRODUCT_FAIL',

    DELETE_PRODUCT_SUCCESS: 'DELETE_PRODUCT_SUCCESS',
    DELETE_PRODUCT_FAIL: 'DELETE_PRODUCT_FAIL',

    GET_PRODUCT_BY_CATEGORY_SUCCESS: 'GET_PRODUCT_BY_CATEGORY_SUCCESS',
    GET_PRODUCT_BY_CATEGORY_FAIL: 'GET_PRODUCT_BY_CATEGORY_FAIL',

    //manager productColor

    ADD_PRODUCT_COLOR_SUCCESS: 'ADD_PRODUCT_COLOR_SUCCESS',
    ADD_PRODUCT_COLOR_FAIL: 'ADD_PRODUCT_COLOR_FAIL',

    GET_ALL_PRODUCT_COLOR_SUCCESS: 'GET_ALL_PRODUCT_COLOR_SUCCESS',
    GET_ALL_PRODUCT_COLOR_FAIL: 'GET_ALL_PRODUCT_COLOR_FAIL',

    GET_AN_PRODUCT_COLOR_SUCCESS: 'GET_AN_PRODUCT_COLOR_SUCCESS',
    GET_AN_PRODUCT_COLOR_FAIL: 'GET_AN_PRODUCT_COLOR_FAIL',

    PUT_PRODUCT_COLOR_SUCCESS: 'PUT_PRODUCT_COLOR_SUCCESS',
    PUT_PRODUCT_COLOR_FAIL: 'PUT_PRODUCT_COLOR_FAIL',

    DELETE_PRODUCT_COLOR_SUCCESS: 'DELETE_PRODUCT_COLOR_SUCCESS',
    DELETE_PRODUCT_COLOR_FAIL: 'DELETE_PRODUCT_COLOR_FAIL',

    //manager cart

    ADD_CART_SUCCESS: 'ADD_CART_SUCCESS',
    ADD_CART_FAIL: 'ADD_CART_FAIL',

    GET_CART_SUCCESS: 'GET_CART_SUCCESS',
    GET_CART_FAIL: 'GET_CART_FAIL',

    PUT_CART_SUCCESS: 'PUT_CART_SUCCESS',
    PUT_CART_FAIL: 'PUT_CART_FAIL',

    DELETE_CART_SUCCESS: 'DELETE_CART_SUCCESS',
    DELETE_CART_FAIL: 'DELETE_CART_FAIL',
};

export default actionTypes;
